import "@/styles/globals.css";
import { inter } from "@/lib/font";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Flysha - Flight Booking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
